### ISSUE TITLE
Error: en.json not included in module.zip

### ISSUE THREAD

**Issue by fluxxdog** [jesshmusic/fvtt-challenge-calculator#2]
`Metadata validation failed for module "fvtt-challenge-calculator": The file "languages/en.json" included by module fvtt-challenge-calculator does not exist`

Looks like the languages folder wasn't included.

**Comment by fluxxdog** [comment]
Tried adding the language manually and:
`Error loading module "D:\Games\Foundry11\Data\modules\fvtt-challenge-calculator\module.json": ENOENT: no such file or directory, open 'D:\Games\Foundry11\Data\modules\fvtt-challenge-calculator\module.json'`

Looking at module.zip, there's a styles directory, scripts directory, a README, modules.json, and license. I'm guessing something didn't properly pack all the files.

**Comment by jesshmusic** [comment]
Oh thanks I will see if I can fix that.

**Comment by jesshmusic** [comment]
I think I figured it out, perhaps if you install now it will work.

**Comment by fluxxdog** [comment]
Installs as expected.
